"""Back up and restore Kitty sessions across all discoverable Kitty servers."""

from __future__ import annotations

import argparse
from datetime import datetime
import os
from pathlib import Path
import stat
import subprocess
import sys
import tempfile
from typing import Sequence


KITTY = "@kitty@"
SOCKET_PREFIX = "kitty-rc-"
SESSION_SUFFIX = ".kitty-session"


def session_directory() -> Path:
    """Return the XDG state directory used for automatically named snapshots."""
    state_home = os.environ.get("XDG_STATE_HOME")
    if state_home:
        return Path(state_home) / "kitty" / "sessions"
    return Path.home() / ".local" / "state" / "kitty" / "sessions"


def discover_sockets() -> list[Path]:
    """Find live-style Kitty remote-control sockets in the current user session."""
    runtime_home = os.environ.get("XDG_RUNTIME_DIR")
    if not runtime_home:
        raise RuntimeError("XDG_RUNTIME_DIR is not set, so Kitty sockets cannot be discovered")

    runtime_dir = Path(runtime_home)
    try:
        entries = tuple(runtime_dir.iterdir())
    except OSError as error:
        raise RuntimeError(f"Cannot inspect {runtime_dir}: {error}") from error

    sockets: list[Path] = []
    for path in entries:
        if not path.name.startswith(SOCKET_PREFIX):
            continue
        try:
            if stat.S_ISSOCK(path.stat().st_mode):
                sockets.append(path)
        except OSError:
            # A Kitty process can exit between listing the directory and stat().
            continue
    return sorted(sockets)


def session_from_socket(socket: Path) -> str:
    """Ask one Kitty server to serialize every OS window it owns."""
    result = subprocess.run(
        [
            KITTY,
            "@",
            "--to",
            f"unix:{socket}",
            "ls",
            "--output-format=session",
        ],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        detail = result.stderr.strip() or result.stdout.strip()
        if not detail:
            detail = f"kitty exited with status {result.returncode}"
        raise RuntimeError(detail)
    return result.stdout.rstrip()


def default_snapshot_path() -> Path:
    timestamp = datetime.now().astimezone().strftime("%Y%m%d-%H%M%S-%f")
    return session_directory() / f"{timestamp}{SESSION_SUFFIX}"


def write_snapshot(
    target: Path,
    sessions: Sequence[tuple[Path, str]],
) -> None:
    """Atomically write combined per-server sessions as one Kitty session file."""
    target.parent.mkdir(mode=0o700, parents=True, exist_ok=True)
    file_descriptor, temporary_name = tempfile.mkstemp(
        dir=target.parent,
        prefix=f".{target.name}.",
    )
    temporary_path = Path(temporary_name)

    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8") as output:
            os.fchmod(output.fileno(), 0o600)
            output.write("# Generated by kitty-session backup.\n")
            output.write("# Restore with: kitty-session restore <this-file>\n")

            for index, (socket, session) in enumerate(sessions):
                if index:
                    # Each server serializes its first OS window without this
                    # marker. Add one when joining independently running servers.
                    output.write("\nnew_os_window\n")
                output.write(f"\n# Source socket: {socket}\n")
                output.write(session)
                output.write("\n")

        os.replace(temporary_path, target)
        os.chmod(target, 0o600)
    except BaseException:
        temporary_path.unlink(missing_ok=True)
        raise


def backup(target_argument: str | None, force: bool, best_effort: bool) -> int:
    target = Path(target_argument).expanduser() if target_argument else default_snapshot_path()
    if target.exists() and not force:
        raise RuntimeError(f"Refusing to overwrite existing snapshot: {target} (use --force to replace it)")

    sockets = discover_sockets()
    if not sockets:
        raise RuntimeError(
            "No Kitty remote-control sockets were found. Start Kitty after activating this configuration."
        )

    sessions: list[tuple[Path, str]] = []
    failures: list[tuple[Path, str]] = []
    for socket in sockets:
        try:
            session = session_from_socket(socket)
        except RuntimeError as error:
            failures.append((socket, str(error)))
            continue
        if session:
            sessions.append((socket, session))

    if failures and not best_effort:
        details = "\n".join(f"  {socket}: {error}" for socket, error in failures)
        raise RuntimeError(
            "Could not back up every discovered Kitty server:\n"
            f"{details}\n"
            "Restart Kitty after activating this configuration, then try again. "
            "Use --best-effort only when omitting inaccessible servers is acceptable."
        )
    if not sessions:
        raise RuntimeError("No Kitty server returned a session to save")

    write_snapshot(target, sessions)
    for socket, error in failures:
        print(f"warning: omitted {socket}: {error}", file=sys.stderr)
    print(f"Saved {len(sessions)} Kitty server session(s) to {target}")
    return 0


def latest_snapshot() -> Path:
    directory = session_directory()
    try:
        snapshots = [path for path in directory.glob(f"*{SESSION_SUFFIX}") if path.is_file()]
    except OSError as error:
        raise RuntimeError(f"Cannot inspect {directory}: {error}") from error
    if not snapshots:
        raise RuntimeError(f"No snapshots found in {directory}")
    return max(snapshots, key=lambda path: path.stat().st_mtime)


def restore(source_argument: str | None) -> int:
    source = Path(source_argument).expanduser() if source_argument else latest_snapshot()
    if not source.is_file():
        raise RuntimeError(f"Snapshot does not exist or is not a file: {source}")

    # Restore intentionally leaves existing Kitty OS windows alone. The session
    # starts a fresh Kitty process and recreates the saved OS-window/tab/pane tree.
    subprocess.Popen([KITTY, "--session", str(source)], start_new_session=True)
    print(f"Started Kitty restore from {source}")
    return 0


def list_snapshots() -> int:
    directory = session_directory()
    try:
        snapshots = sorted(
            (path for path in directory.glob(f"*{SESSION_SUFFIX}") if path.is_file()),
            key=lambda path: path.stat().st_mtime,
            reverse=True,
        )
    except OSError as error:
        raise RuntimeError(f"Cannot inspect {directory}: {error}") from error

    for path in snapshots:
        print(path)
    return 0


def parse_arguments(arguments: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Back up and restore Kitty sessions across all Kitty OS windows.",
    )
    subcommands = parser.add_subparsers(dest="command", required=True)

    backup_parser = subcommands.add_parser("backup", help="write a session snapshot")
    backup_parser.add_argument("path", nargs="?", help="output file (default: timestamped XDG state path)")
    backup_parser.add_argument("--force", action="store_true", help="replace an existing output file")
    backup_parser.add_argument(
        "--best-effort",
        action="store_true",
        help="save accessible servers even if another Kitty socket cannot be queried",
    )

    restore_parser = subcommands.add_parser("restore", help="open a saved session in new Kitty OS windows")
    restore_parser.add_argument("path", nargs="?", help="snapshot file (default: most recent snapshot)")

    subcommands.add_parser("list", help="list automatically named snapshots")
    return parser.parse_args(arguments)


def main(arguments: Sequence[str] | None = None) -> int:
    args = parse_arguments(arguments)
    try:
        if args.command == "backup":
            return backup(args.path, args.force, args.best_effort)
        if args.command == "restore":
            return restore(args.path)
        return list_snapshots()
    except RuntimeError as error:
        print(f"kitty-session: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
