# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  zfsMountOptions = [ "nofail" "x-systemd-mount-timeout=60" ];
in
{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Root filesystem (adjust as needed for your VM setup)
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/ESP";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/bank" = {
    device = "bank";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  fileSystems."/bank/data" = {
    device = "bank/data";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  fileSystems."/bank/data/docs" = {
    device = "bank/data/docs";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  fileSystems."/bank/data/backups" = {
    device = "bank/data/backups";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  fileSystems."/bank/data/pictures" = {
    device = "bank/data/pictures";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  fileSystems."/bank/data/media" = {
    device = "bank/data/media";
    fsType = "zfs";
    options = zfsMountOptions;
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eth0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
